### ISSUE TITLE
"That's not valid number" error

### ISSUE THREAD

**Issue by TheDanikReal** [Ch1ll-Studio/SparkV#204]
- [] This feature request is related to an on going problem.
 **Problem**
When i try to write  */music song  action: volume number: 99*
It giving me error *That's not valid number!*

**The expected behavior**
I expected to *changing volume of song playing right now.*

**Comment by TheDanikReal** [comment]
![IMG_20220507_215022](https://user-images.githubusercontent.com/99135042/167268054-7980fa94-8935-457d-9ccd-f82a3a6e5059.jpg)

**Comment by KingCh1ll** [comment]
Fixed in the next update.

**Comment by TheDanikReal** [comment]
> Fixed in the next update.

It's good if I write in github instead of writing in discord, since i seem to been banned from the your server
